name: krypto
description: Gerador de senhas Krypto.
version: 2.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_admob_flutter: ^1.0.1
  get: ^3.24.0
  intl: ^0.16.1
  permission_handler: ^6.0.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png